language: python
python:
 - "2.7"

before_script:
 - export LD_LIBRARY_PATH=`pwd`/samples/:$LD_LIBRARY_PATH
 - export cc=gcc
 - sudo chmod +x decoder.py
 - sudo chmod +x install.py
 - sudo chmod +x .travis.sh
 - sudo ./install.py --unicorn --capstone

script: ./.travis.sh

compiler:
 - gcc

os:
 - linux

install:
 - sudo apt-get update -y
 - sudo apt-get install -y libglib2.0-dev