language: python
python:
 - "2.7"

before_script:
 - sudo chmod +x decoder.py
 - sudo chmod +x install.py
 - sudo chmod +x .travis.sh
 - sudo ./install.py --unicorn --capstone

script: ./.travis.sh

compiler:
 - gcc

os:
 - linux

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libglib2.0-dev